[build]
  command = "bun run build"
  publish = ".output/public"

[functions]
  directory = ".output/server"

[[redirects]]
  from = "/_netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
